spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airlinebooking
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
